steps:

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/serabutinn', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/serabutinn']
  
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'serabutinn'
      - '--image'
      - 'gcr.io/$PROJECT_ID/serabutinn'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'PROJECT_ID=${PROJECT_ID}'
      - '--set-secrets'
      - 'JWT_SECRET=JWT_SECRET:latest,JWT_AUD=JWT_AUD:latest,JWT_ISS=JWT_ISS:latest,JWT_SUB=JWT_SUB:latest,JWT_EXPIRES_IN=JWT_EXPIRES_IN:latest,MIDTRANS_SERVER_KEY=MIDTRANS_SERVER_KEY:latest,MIDTRANS_CLIENT_KEY=MIDTRANS_CLIENT_KEY:latest,PROFILE_PICTURE_DEFAULT=PROFILE_PICTURE_DEFAULT:latest,BUCKET_NAME=BUCKET_NAME:latest'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: asia-southeast2

images:
  - 'gcr.io/$PROJECT_ID/serabutinn'